CREATE TABLE educations (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  degree VARCHAR(255) NOT NULL,
  field VARCHAR(255),
  institution VARCHAR(255) NOT NULL,
  location VARCHAR(255),
  start_date DATE NOT NULL,
  end_date DATE,
  current BOOLEAN DEFAULT false,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);